/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewProject;

import usuario.DAO.ConsultaUsuDAO;
import baseProject.Cadastro;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cauet Damasceno
 */
public class TelaConsultaUsuario extends javax.swing.JInternalFrame {

    Cadastro cad = new Cadastro();

    /**
     * Creates new form TelaConsultaUsuario
     */
    public TelaConsultaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsul = new javax.swing.JTable();
        btnCap = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jctipo = new javax.swing.JComboBox<>();
        jtarg = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consulta de usuários");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tbConsul.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID.", "Nome", "Telefone", "Login"
            }
        ));
        jScrollPane1.setViewportView(tbConsul);
        if (tbConsul.getColumnModel().getColumnCount() > 0) {
            tbConsul.getColumnModel().getColumn(0).setMinWidth(40);
            tbConsul.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        btnCap.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauet Damasceno\\Documents\\NetBeansProjects\\VaccineForAll\\src\\main\\java\\imagens\\captura-de-tela.png")); // NOI18N
        btnCap.setText("Capturar");
        btnCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauet Damasceno\\Documents\\NetBeansProjects\\VaccineForAll\\src\\main\\java\\imagens\\exit.png")); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jctipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Login" }));

        jtarg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtargKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jctipo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtarg, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCap, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jctipo, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jtarg))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setBounds(30, 10, 840, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        DefaultTableModel mp1 = (DefaultTableModel) tbConsul.getModel();
        int l = mp1.getRowCount();

        if (l > 0) {
            while (l > 0) {
                ((DefaultTableModel) tbConsul.getModel()).removeRow(l - 1); // -1 pois a primeira linha é a linha ZERO
                l--;
            }
        } // Fim do while

        try {
            // Sem argumento na pesquisa:
            ResultSet rs = ConsultaUsuDAO.carregaTabela();

            // Instancia o objeto mp da classe DefaultTableModel
            DefaultTableModel mp = (DefaultTableModel) tbConsul.getModel();

            while (rs.next()) {
                // pega os dados da linha no banco de dados:
                String Coluna0 = rs.getString("iduser").toString().trim();
                String Coluna1 = rs.getString("nome").toString().trim();
                String Coluna2 = rs.getString("fone").toString().trim();
                String Coluna3 = rs.getString("login").toString().trim();

                mp.addRow(new String[]{Coluna0, Coluna1, Coluna2, Coluna3});

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro:" + e, "Preencher Item", 2);
        }
        tamanhocolunas();
        tbConsul.setAutoCreateRowSorter(true);// ordena as linhas ao clicar na coluna.
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapActionPerformed
        // TODO add your handling code here:
        int row = tbConsul.getSelectedRow();        
        cad.setIduser(Integer.parseInt((tbConsul.getValueAt(row, 0).toString().trim())));
        TelaCadastroUsuarios.recebeid(cad);
        dispose();
    }//GEN-LAST:event_btnCapActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void jtargKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtargKeyReleased
        // TODO add your handling code here:
        
        String escolha = jctipo.getSelectedItem().toString().trim();
        String tipo = escolha.toLowerCase();        
        // System.out.println(tipo);
        String arg = jtarg.getText();

        DefaultTableModel mp1 = (DefaultTableModel) tbConsul.getModel();
        int l = mp1.getRowCount();

        if (l > 0) {
            while (l > 0) {
                ((DefaultTableModel) tbConsul.getModel()).removeRow(l - 1); // menos um pois a primeira  linha é zero
                l--;
            }//  fim do while
        }// fim do if-verifica se tem alguma informação tabela

        // fim do limpa a tabela
        try {
            ResultSet rs = ConsultaUsuDAO.getResultSet(tipo, arg);

            DefaultTableModel mp = (DefaultTableModel) tbConsul.getModel();

            while (rs.next()) {
                // pega os dados da linha do banco de dados
                String Coluna0 = rs.getString("iduser").toString().trim();
                String Coluna1 = rs.getString("nome").toString().trim();
                String Coluna2 = rs.getString("fone").toString().trim();
                String Coluna3 = rs.getString("login").toString().trim();
              
                
                // preenche a linha JTable e volta  para o while até terminar as linhas contidas
                // na tabela do banco.
                mp.addRow(new String[] {Coluna0,Coluna1,Coluna2,Coluna3});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro:"+e, "Preencher Item",2);
        }
        
        tamanhocolunas();
        tbConsul.setAutoCreateRowSorter(true); // ordena as linhas ao clicar na coluna

    }//GEN-LAST:event_jtargKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCap;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JComboBox<String> jctipo;
    private javax.swing.JTextField jtarg;
    private javax.swing.JTable tbConsul;
    // End of variables declaration//GEN-END:variables

    public void tamanhocolunas() {
        tbConsul.getColumnModel().getColumn(0).setMinWidth(100);
        tbConsul.getColumnModel().getColumn(1).setMinWidth(250);
    }// Fim dimensionar a tabela.

}
