/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewProject;

import javax.swing.JOptionPane;


/**
 *
 * @author Cauet Damasceno
 */
public class TelaPrincipal extends javax.swing.JFrame {

    public static boolean telcad;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UsuarioLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        MenuCadUsu = new javax.swing.JMenuItem();
        MenuCadPac = new javax.swing.JMenuItem();
        MenuRel = new javax.swing.JMenu();
        MenuRelVac = new javax.swing.JMenuItem();
        MenuRelTabVac = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        MenuAjudSobre = new javax.swing.JMenuItem();
        MenuOpc = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuOpcSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 849, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(Desktop);
        Desktop.setBounds(0, 0, 849, 540);

        jPanel1.setLayout(null);

        jLabel1.setText("Usuário:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 300, 80, 16);

        UsuarioLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UsuarioLabel.setText("Usuário");
        jPanel1.add(UsuarioLabel);
        UsuarioLabel.setBounds(10, 320, 170, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauet Damasceno\\Documents\\NetBeansProjects\\VaccineForAll\\src\\main\\java\\imagens\\logo_fundo_azul.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 355, 180, 180);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(849, 0, 190, 540);

        MenuCadastro.setText("Cadastro");
        MenuCadastro.setEnabled(false);

        MenuCadUsu.setText("Usuario");
        MenuCadUsu.setEnabled(false);
        MenuCadUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadUsuActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadUsu);

        MenuCadPac.setText("Paciente");
        MenuCadPac.setEnabled(false);
        MenuCadPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadPacActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadPac);

        jMenuBar1.add(MenuCadastro);

        MenuRel.setText("Relatório");

        MenuRelVac.setText("Relatório de vacinação");
        MenuRelVac.setEnabled(false);
        MenuRelVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelVacActionPerformed(evt);
            }
        });
        MenuRel.add(MenuRelVac);

        MenuRelTabVac.setText("Tabela com fila de vacinação com prioridade e confirmação");
        MenuRelTabVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuRelTabVacActionPerformed(evt);
            }
        });
        MenuRel.add(MenuRelTabVac);

        jMenuBar1.add(MenuRel);

        MenuAjuda.setText("Ajuda");

        MenuAjudSobre.setText("Sobre");
        MenuAjudSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAjudSobreActionPerformed(evt);
            }
        });
        MenuAjuda.add(MenuAjudSobre);

        jMenuBar1.add(MenuAjuda);

        MenuOpc.setText("Opções");

        jMenuItem1.setText("Trocar conta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuOpc.add(jMenuItem1);

        MenuOpcSair.setText("Sair");
        MenuOpcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuOpcSairActionPerformed(evt);
            }
        });
        MenuOpc.add(MenuOpcSair);

        jMenuBar1.add(MenuOpc);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1048, 603));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuOpcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuOpcSairActionPerformed
        // Função do botão sair
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_MenuOpcSairActionPerformed

    private void MenuAjudSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAjudSobreActionPerformed
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);

    }//GEN-LAST:event_MenuAjudSobreActionPerformed

    private void MenuCadUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadUsuActionPerformed
        // TODO add your handling code here:
        
        TelaCadastroUsuarios cadastroUsuarios = new TelaCadastroUsuarios();
        cadastroUsuarios.setVisible(true);
        Desktop.add(cadastroUsuarios);
        

    }//GEN-LAST:event_MenuCadUsuActionPerformed

    private void MenuCadPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadPacActionPerformed
        // TODO add your handling code here:
        
        TelaCadastroPaciente cadastroPaciente = new TelaCadastroPaciente();
        cadastroPaciente.setVisible(true);
        Desktop.add(cadastroPaciente);
        
    }//GEN-LAST:event_MenuCadPacActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        

    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TelaLogin trocarUsuario = new TelaLogin();
        trocarUsuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuRelVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelVacActionPerformed
        // TODO add your handling code here:
        TelaRelatorioVac relatorioVac = new TelaRelatorioVac();
        relatorioVac.setVisible(true);
        Desktop.add(relatorioVac);
       
    }//GEN-LAST:event_MenuRelVacActionPerformed

    private void MenuRelTabVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuRelTabVacActionPerformed
        // TODO add your handling code here:
        TelaConfirmacaoVac confirmavac = new TelaConfirmacaoVac();
        confirmavac.setVisible(true);
        Desktop.add(confirmavac);
        
    }//GEN-LAST:event_MenuRelTabVacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem MenuAjudSobre;
    private javax.swing.JMenu MenuAjuda;
    public static javax.swing.JMenuItem MenuCadPac;
    public static javax.swing.JMenuItem MenuCadUsu;
    public static javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuOpc;
    private javax.swing.JMenuItem MenuOpcSair;
    private javax.swing.JMenu MenuRel;
    private javax.swing.JMenuItem MenuRelTabVac;
    public static javax.swing.JMenuItem MenuRelVac;
    public static javax.swing.JLabel UsuarioLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
