/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewProject;

import baseProject.Paciente;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pacienteDAO.PacienteDAO;

/**
 *
 * @author Cauet Damasceno
 */
public class TelaConfirmacaoVac extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaConfirmacaoVac
     */
    public TelaConfirmacaoVac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtRelatorio = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jtRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID.", "Nome", "Telefone", "Idade", "Prioridade"
            }
        ));
        jScrollPane1.setViewportView(jtRelatorio);

        jButton2.setText("Confirmar vacinação");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sair");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        // TODO add your handling code here:
        DefaultTableModel mp1 = (DefaultTableModel) jtRelatorio.getModel();
        int l = mp1.getRowCount();

        if (l > 0) {
            while (l > 0) {
                ((DefaultTableModel) jtRelatorio.getModel()).removeRow(l - 1); // -1 pois a primeira linha é a linha ZERO
                l--;
            }
        } // Fim do while

        try {
            // Sem argumento na pesquisa:
            PacienteDAO paciente = new PacienteDAO();

            // Instancia o objeto mp da classe DefaultTableModel
            DefaultTableModel mp = (DefaultTableModel) jtRelatorio.getModel();

            List<Paciente> pacientes = paciente.carregarLista();

            for (Paciente pacientx : pacientes) {
                if(pacientx.getPac_dtvacinacao() == null) {
                    int age = pacientx.getPac_idade();
                    int area = pacientx.getPac_area_saude();
                    String prioridade = "0";

                    String id = Integer.toString(pacientx.getPac_id());
                    String nome = pacientx.getPac_nome();
                    String telefone = pacientx.getPac_tel();
                    int idade = pacientx.getPac_idade();

                    if (age >= 70) {
                        prioridade = "1";
                    } else if (area == 1 && age < 70) {
                        prioridade = "2";
                    } else {
                        prioridade = "3";
                    }

                    mp.addRow(new String[]{id, nome, telefone, String.valueOf(idade), prioridade});
                }               
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro:" + e, "Preencher Item", 2);
        }
        tamanhocolunas();
        jtRelatorio.setAutoCreateRowSorter(true);


    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = jtRelatorio.getSelectedRow();

        int id = (Integer.parseInt((jtRelatorio.getValueAt(row, 0).toString().trim())));
        PacienteDAO pacDAO = new PacienteDAO();
        JOptionPane.showMessageDialog(this, "Vacinação confirmada");

        try {
            pacDAO.alterarData(id);
            jtRelatorio.remove(row);

        } catch (Exception e) {
            
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtRelatorio;
    // End of variables declaration//GEN-END:variables

    public void tamanhocolunas() {
        jtRelatorio.getColumnModel().getColumn(0).setMinWidth(100);
        jtRelatorio.getColumnModel().getColumn(1).setMinWidth(250);
    }// Fim dimensionar a tabela.

}
