/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewProject;

import baseProject.Paciente;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.Period;
import java.util.Calendar;
import java.util.Date;

import java.util.List;
import java.util.Locale;
import java.util.concurrent.TimeUnit;

import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pacienteDAO.PacienteDAO;

/**
 *
 * @author Cauet Damasceno
 */
public class TelaRelatorioVac extends javax.swing.JInternalFrame {

    Paciente paci = new Paciente();
    PacienteDAO pacDAO;
    DateFormat format;

    /**
     * Creates new form TelaRelatorioVac
     */
    public TelaRelatorioVac() {
        initComponents();
    }
    double grupo1;
    double grupo2;
    double grupo3;
    double grupo4;
    double media1;
    double media2;
    double media3;
    double media4;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRelatorio = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();
        jDataInicio = new com.toedter.calendar.JDateChooser();
        jDataFim = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPesq = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(843, 494));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jtRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Faixa etaria", "Média diária"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtRelatorio.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtRelatorio.setAutoscrolls(false);
        jScrollPane1.setViewportView(jtRelatorio);

        btnSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauet Damasceno\\Documents\\NetBeansProjects\\VaccineForAll\\src\\main\\java\\imagens\\exit.png")); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Data inicio:");

        jLabel2.setText("Data Fim:");

        btnPesq.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauet Damasceno\\Documents\\NetBeansProjects\\VaccineForAll\\src\\main\\java\\imagens\\search.png")); // NOI18N
        btnPesq.setText("Pesquisar");
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(124, 124, 124))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPesq)
                        .addComponent(btnSair))
                    .addComponent(jDataFim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        DefaultTableModel mp1 = (DefaultTableModel) jtRelatorio.getModel();
        int l = mp1.getRowCount();

        if (l > 0) {
            while (l > 0) {
                ((DefaultTableModel) jtRelatorio.getModel()).removeRow(l - 1); // -1 pois a primeira linha é a linha ZERO
                l--;
            }
        } // Fim do while

        tamanhocolunas();
        jtRelatorio.setAutoCreateRowSorter(true);


    }//GEN-LAST:event_formInternalFrameOpened

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
        // Este método carrega os dados do DB:
        DefaultTableModel mp1 = (DefaultTableModel) jtRelatorio.getModel();
        int l = mp1.getRowCount();

        if (l > 0) {
            while (l > 0) {
                ((DefaultTableModel) jtRelatorio.getModel()).removeRow(l - 1); // -1 pois a primeira linha é a linha ZERO
                l--;
            }
        } // Fim do while

        try {
            // Sem argumento na pesquisa:
            PacienteDAO pacienteDAO = new PacienteDAO();

            // Instancia o objeto mp da classe DefaultTableModel
            DefaultTableModel mp = (DefaultTableModel) jtRelatorio.getModel();

            // Carrega todos os pacientes
            List<Paciente> pacientes = pacienteDAO.carregarLista();
            //System.out.println(jDataInicio.getDate());
            //System.out.println(jDataFim.getDate());
            // Armazena pacientes filtrados por periodo de data
            List<Paciente> pacientesNoPeriodo = pacientes
                    .stream()
                    .filter(p -> p.getPac_dtvacinacao() != null && p.getPac_dtvacinacao().after(jDataInicio.getDate()) && p.getPac_dtvacinacao().before(jDataFim.getDate()))
                    .collect(Collectors.toList());

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

            String dataInicio = sdf.format(jDataInicio.getDate());
            String dataFim = sdf.format(jDataFim.getDate());
            Date DataInicio = sdf.parse(dataInicio);
            Date DataFim = sdf.parse(dataFim);
            long diff = DataFim.getTime() - DataInicio.getTime();
            TimeUnit time = TimeUnit.DAYS;
            long diasUteis = time.convert(diff, TimeUnit.MILLISECONDS);

            for (Paciente pacientex : pacientesNoPeriodo) {

                if (pacientex.getPac_idade() >= 90) {
                    grupo1++;
                } else if (pacientex.getPac_idade() >= 70 && pacientex.getPac_idade() < 90) {
                    grupo2++;
                } else if (pacientex.getPac_idade() >= 50 && pacientex.getPac_idade() < 70) {
                    grupo3++;
                } else {
                    grupo4++;
                }

            }
            media1 = grupo1 / diasUteis;
            media2 = grupo2 / diasUteis;
            media3 = grupo3 / diasUteis;
            media4 = grupo4 / diasUteis;

            mp.addRow(new String[]{"Pessoas acima de 90", String.format("%.2f", media1)});
            mp.addRow(new String[]{"Pessoas acima de 70 e abaixo de 90", String.format("%.2f", media2)});
            mp.addRow(new String[]{"Pessoas acima de 50 e abaixo de 70", String.format("%.2f",media3)});
            mp.addRow(new String[]{"Pessoas abaixo 50", String.format("%.2f",media4)});

            // Verifica prioridade dos pacientes por criterios
            // System.out.println("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro:" + e, "Preencher Item", 2);
        }

        tamanhocolunas();
        jtRelatorio.setAutoCreateRowSorter(true);


    }//GEN-LAST:event_btnPesqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesq;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDataFim;
    private com.toedter.calendar.JDateChooser jDataInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtRelatorio;
    // End of variables declaration//GEN-END:variables

    public void tamanhocolunas() {
        jtRelatorio.getColumnModel().getColumn(0).setMinWidth(100);
        jtRelatorio.getColumnModel().getColumn(1).setMinWidth(250);
    }// Fim dimensionar a tabela.

}
