/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewProject;

import conexao.ConexaoDB;
import baseProject.Usuario;
import usuario.DAO.UsuarioDAO;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Cauet Damasceno
 */
public class TelaLogin extends javax.swing.JFrame {
    
    Connection conexao;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
         // A linha abaixo serve de apoio para saber o status da conexão com o banco de dados:
        conexao = ConexaoDB.obtemConexao();
        System.out.println(conexao);
        if (conexao != null) {
            StatusLabel.setText("Conectado");
        } else {
            StatusLabel.setText("Não Conectado");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginTextField = new javax.swing.JTextField();
        SenhaPasswordField = new javax.swing.JPasswordField();
        SairButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        StatusLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(321, 246));
        setResizable(false);
        getContentPane().setLayout(null);

        LoginTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite seu Login:"));
        getContentPane().add(LoginTextField);
        LoginTextField.setBounds(310, 30, 225, 55);

        SenhaPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite sua senha:"));
        getContentPane().add(SenhaPasswordField);
        SenhaPasswordField.setBounds(310, 100, 225, 55);

        SairButton.setText("Sair");
        SairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SairButton);
        SairButton.setBounds(310, 170, 95, 33);

        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(LoginButton);
        LoginButton.setBounds(440, 170, 95, 33);
        getContentPane().add(StatusLabel);
        StatusLabel.setBounds(6, 240, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauet Damasceno\\Documents\\NetBeansProjects\\VaccineForAll\\src\\main\\java\\imagens\\tela_login.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 680, 290);

        setSize(new java.awt.Dimension(588, 268));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SairButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        // pegar os dados informados
        String usuario = LoginTextField.getText();
        String senha = String.valueOf(SenhaPasswordField.getPassword());

        // Preparar para conectar com o banco:
        try {
            // Criando um objeto do tipo usuario:
            Usuario u = new Usuario();
            u.setUsuario(usuario);
            u.setSenha(senha);

            // Criando um usuarioDAO:
            UsuarioDAO uDAO = new UsuarioDAO();
            if (uDAO.existe(u)) {
                // JOptionPane.showMessageDialog(this, "Bem vindo," + u.getUsuario() + "!");
                // Abrir a tela:
                TelaPrincipal principal = new TelaPrincipal();
                principal.setVisible(true);
               dispose();
            }
            conexao.close();
            this.dispose();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Problemas técnicos, tente mais tarde!");
            ex.printStackTrace();

        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField LoginTextField;
    private javax.swing.JButton SairButton;
    private javax.swing.JPasswordField SenhaPasswordField;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
