/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewProject;

import baseProject.Paciente;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import pacienteDAO.ColsultaPacDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cauet Damasceno
 */
public class TelaConsultaPaciente extends javax.swing.JInternalFrame {

    Paciente paci = new Paciente();

    /**
     * Creates new form TelaConsultaPaciente
     */
    public TelaConsultaPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsulta = new javax.swing.JTable();
        btnCapturar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jctipo = new javax.swing.JComboBox<>();
        jtarg = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consulta de pacientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID.", "Nome", "Telefone", "Idade", "Endereço", "RG", "Área da saúde"
            }
        ));
        tbConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(tbConsulta);
        if (tbConsulta.getColumnModel().getColumnCount() > 0) {
            tbConsulta.getColumnModel().getColumn(0).setMinWidth(30);
            tbConsulta.getColumnModel().getColumn(0).setMaxWidth(30);
            tbConsulta.getColumnModel().getColumn(1).setMinWidth(170);
            tbConsulta.getColumnModel().getColumn(1).setMaxWidth(170);
            tbConsulta.getColumnModel().getColumn(2).setMinWidth(75);
            tbConsulta.getColumnModel().getColumn(2).setMaxWidth(75);
            tbConsulta.getColumnModel().getColumn(3).setMinWidth(50);
            tbConsulta.getColumnModel().getColumn(3).setMaxWidth(50);
            tbConsulta.getColumnModel().getColumn(4).setMinWidth(170);
            tbConsulta.getColumnModel().getColumn(4).setMaxWidth(170);
            tbConsulta.getColumnModel().getColumn(5).setMinWidth(90);
            tbConsulta.getColumnModel().getColumn(5).setMaxWidth(90);
            tbConsulta.getColumnModel().getColumn(6).setMinWidth(90);
            tbConsulta.getColumnModel().getColumn(6).setMaxWidth(90);
        }

        btnCapturar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauet Damasceno\\Documents\\NetBeansProjects\\VaccineForAll\\src\\main\\java\\imagens\\captura-de-tela.png")); // NOI18N
        btnCapturar.setText("Capturar");
        btnCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cauet Damasceno\\Documents\\NetBeansProjects\\VaccineForAll\\src\\main\\java\\imagens\\exit.png")); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jctipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "RG" }));

        jtarg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtargKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jctipo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtarg, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCapturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jctipo, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jtarg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCapturar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair)
                        .addGap(0, 314, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtargKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtargKeyReleased
        String escolha = jctipo.getSelectedItem().toString().trim();
        String tipo = escolha.toLowerCase();
        // System.out.println(tipo);
        String arg = jtarg.getText();

        DefaultTableModel mp1 = (DefaultTableModel) tbConsulta.getModel();
        int l = mp1.getRowCount();

        if (l > 0) {
            while (l > 0) {
                ((DefaultTableModel) tbConsulta.getModel()).removeRow(l - 1); // menos um pois a primeira  linha é zero
                l--;
            }//  fim do while
        }// fim do if-verifica se tem alguma informação tabela

        // fim do limpa a tabela
        try {
            ResultSet rs = ColsultaPacDAO.getResultSet(tipo, arg);

            DefaultTableModel mp = (DefaultTableModel) tbConsulta.getModel();

            while (rs.next()) {
                // pega os dados da linha do banco de dados
                String Coluna0 = rs.getString("pac_id").toString().trim();
                String Coluna1 = rs.getString("pac_nome").toString().trim();
                String Coluna2 = rs.getString("pac_tel").toString().trim();
                String Coluna3 = rs.getString("pac_idade").toString().trim();
                String Coluna4 = rs.getString("pac_ende").toString().trim();
                String Coluna5 = rs.getString("pac_rg").toString().trim();
                String statusSaude = rs.getString("pac_area_saude").toString().trim();
                String Coluna6 = "";
                if (statusSaude.equals("1")) {
                    Coluna6 = "Sim";
                }
                if (statusSaude.equals("0")) {
                    Coluna6 = "Não";
                }

                // preenche a linha JTable e volta  para o while até terminar as linhas contidas
                // na tabela do banco.
                mp.addRow(new String[]{Coluna0, Coluna1, Coluna2, Coluna3, Coluna4, Coluna5, Coluna6});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro:" + e, "Preencher Item", 2);
        }

        tamanhocolunas();
        tbConsulta.setAutoCreateRowSorter(true); // ordena as linhas ao clicar na coluna


    }//GEN-LAST:event_jtargKeyReleased

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarActionPerformed
        // TODO add your handling code here:
        int row = tbConsulta.getSelectedRow();
        paci.setPac_id(Integer.parseInt((tbConsulta.getValueAt(row, 0).toString().trim())));
        TelaCadastroPaciente.recebeid(paci);
        dispose();
    }//GEN-LAST:event_btnCapturarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        DefaultTableModel mp1 = (DefaultTableModel) tbConsulta.getModel();
        int l = mp1.getRowCount();

        if (l > 0) {
            while (l > 0) {
                ((DefaultTableModel) tbConsulta.getModel()).removeRow(l - 1);// -1 pois a primeira linha é = 0.
                l--;
            }
        } // Fim do while

        try {
            // Sem argumento na pesquisa:
            ResultSet rs = ColsultaPacDAO.carregaTabela();

            // Instancia o objeto mp da classe DefaultTableModel
            DefaultTableModel mp = (DefaultTableModel) tbConsulta.getModel();

            while (rs.next()) {
                // pega os dados da linha no banco:
                String Coluna0 = rs.getString("pac_id").toString().trim();
                String Coluna1 = rs.getString("pac_nome").toString().trim();
                String Coluna2 = rs.getString("pac_tel").toString().trim();
                String Coluna3 = rs.getString("pac_idade").toString().trim();
                String Coluna4 = rs.getString("pac_ende").toString().trim();
                String Coluna5 = rs.getString("pac_rg").toString().trim();
                String statusSaude = rs.getString("pac_area_saude").toString().trim();
                String Coluna6 = "";
                if (statusSaude.equals("1")) {
                    Coluna6 = "Sim";
                }
                if (statusSaude.equals("0")) {
                    Coluna6 = "Não";
                }
                // preenche a linha JTable e volta para o while até terminar as linhas
                // contidas na tabela do banco.
                mp.addRow(new String[]{Coluna0, Coluna1, Coluna2, Coluna3, Coluna4, Coluna5, Coluna6});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro:" + e, "Preencher Item", 2);
        }
        tamanhocolunas();
        tbConsulta.setAutoCreateRowSorter(true); // ordena as linhas ao clicar na coluna.
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturar;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jctipo;
    private javax.swing.JTextField jtarg;
    private javax.swing.JTable tbConsulta;
    // End of variables declaration//GEN-END:variables

    public void tamanhocolunas() {
        tbConsulta.getColumnModel().getColumn(0).setMinWidth(100);
        tbConsulta.getColumnModel().getColumn(1).setMinWidth(250);
    }// Fim dimensionar a tabela.

}
